// Master content-publishing orchestrator — the ONE command to publish
// courses / coding problems / mock exam banks without hand-running each
// importer yourself in the right order with the right env per target.
//
// Usage (from repo root):
//   npx tsx scripts/publish-content.ts --target <local|production> --all
//   npx tsx scripts/publish-content.ts --target <local|production> --mock-exams
//   npx tsx scripts/publish-content.ts --target <local|production> --coding-problems
//   npx tsx scripts/publish-content.ts --target <local|production> --courses=<slug>[,<slug>...]
//
// --target is always required — there is no default, so this can never be
// run against the wrong environment by omission.
//
// Credentials for --target production come from scripts/.env.production
// (gitignored, never committed — see .env.production.example alongside
// this file) via dotenv; explicit environment variables you export
// yourself always take precedence over that file (dotenv's default
// behavior — it never overwrites an already-set process.env value).
//
// HTTP-API auth: IMPORT_TOOL_SECRET (preferred) skips /auth/login and its
// recaptcha gate entirely, via apps/api's 'importTool' security scheme
// (tsoaAuth.ts) — required in practice, since RECAPTCHA_REQUIRED defaults
// true in production and a reCAPTCHA v2 token can't be generated by a CLI
// script anyway. IMPORT_ADMIN_EMAIL is required either way (selects which
// ADMIN user the secret path attaches, or which account the fallback
// password-login uses). See .env.production.example.
//
// SCOPE NOTE: the course step here drives import-docusaurus-course.ts
// (apps/api/scripts/), which imports Docusaurus-sourced courses
// (apps/docs/docs/<slug>) — the ~24-course TARGET_COURSES allowlist baked
// into that script. It does NOT drive apps/web/scripts/import-authored-
// course.mjs (the life-skills / DB-commands / metrics-course family
// staged under apps/web/scratch/), because that importer takes bespoke
// per-course arguments (--name, --input directory, --roles, --publish)
// with no existing slug→args manifest to automate generically — inventing
// one would mean deciding content scope on your behalf. Those still get
// published by hand, one `import-authored-course.mjs` invocation at a
// time, until/unless you want a manifest built for this script to drive.
//
// SCOPE NOTE 2: apps/api/scripts/check-course-import.mjs was NOT reused
// for the verify step — reading it, it turned out to be an ad-hoc tool
// hardcoded to exactly two course slugs (agentic-ai-fundamentals,
// git-github-actions) left over from a past task, with a --verify-web
// flag that hits a local-only hostname (next.sypher.local) and a
// --probe-import flag that POSTs deliberately-invalid payloads to test
// validation — none of that generalizes to "verify whatever was just
// published," and --verify-web would be actively wrong against
// production. The verify step below is a small inline replacement:
// log in, list the course catalog, and confirm the course(s) this run
// actually touched are present with a sane module count. Read-only.

import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const API_DIR = path.join(REPO_ROOT, 'apps', 'api');

type Target = 'local' | 'production';

// ── Argument parsing ────────────────────────────────────────────────────

function parseArgs(argv: string[]) {
  const args = {
    target: null as Target | null,
    all: false,
    mockExams: false,
    codingProblems: false,
    courses: null as string[] | null,
  };
  for (const raw of argv) {
    if (raw === '--all') args.all = true;
    else if (raw === '--mock-exams') args.mockExams = true;
    else if (raw === '--coding-problems') args.codingProblems = true;
    else if (raw.startsWith('--courses=')) args.courses = raw.slice('--courses='.length).split(',').map((s) => s.trim()).filter(Boolean);
    else if (raw === '--target=local' || raw === '--target' && false) { /* handled below */ }
    else if (raw.startsWith('--target=')) args.target = raw.slice('--target='.length) as Target;
  }
  // support `--target production` (space form) alongside `--target=production`
  const tIdx = argv.indexOf('--target');
  if (tIdx !== -1 && argv[tIdx + 1]) args.target = argv[tIdx + 1] as Target;

  if (args.target !== 'local' && args.target !== 'production') {
    fail('--target local|production is required (no default, on purpose).');
  }
  if (!args.all && !args.mockExams && !args.codingProblems && !args.courses) {
    fail('Nothing to do — pass --all, --mock-exams, --coding-problems, or --courses=<slug>[,<slug>...].');
  }
  return args as { target: Target; all: boolean; mockExams: boolean; codingProblems: boolean; courses: string[] | null };
}

function fail(message: string): never {
  console.error(`\nERROR: ${message}\n`);
  process.exit(1);
}

// ── Structural safety guard — not a list omission, a standing assertion ─
// Checked against every single step before it runs, unconditionally, so a
// future edit that adds seed-corporate-test.ts back into the STEPS array
// below still can't make it execute under --target production.

const FORBIDDEN_IN_PRODUCTION = ['seed-corporate-test'];

function assertNotForbidden(target: Target, scriptPath: string) {
  if (target !== 'production') return;
  const base = path.basename(scriptPath);
  if (FORBIDDEN_IN_PRODUCTION.some((f) => base.includes(f))) {
    // Deliberately not a normal `fail()` — this must be impossible to
    // route around from inside the STEPS list, so it throws directly.
    throw new Error(
      `REFUSING: "${base}" is hard-forbidden from running under --target production ` +
      `(dev-only fixture — TESTCO company + hardcoded "password" login). This check is ` +
      `structural, not a list omission — remove it from FORBIDDEN_IN_PRODUCTION in ` +
      `scripts/publish-content.ts if you genuinely need to override it, which you don't.`,
    );
  }
}

// ── Credentials / connection resolution per target ──────────────────────

function loadProductionEnvFile() {
  const envFile = path.join(__dirname, '.env.production');
  if (existsSync(envFile)) {
    dotenv.config({ path: envFile }); // never overwrites an already-exported var
  }
}

function resolveHttpEnv(target: Target): Record<string, string> {
  const apiUrl = target === 'production' ? 'https://api.syphernext.com' : 'http://localhost:4000';
  if (target === 'production') {
    // Either the importTool secret (preferred — skips /auth/login and its
    // recaptcha gate entirely) or full admin credentials must be present;
    // never fall back to the dev-seed defaults, never prompt interactively.
    const hasSecret = Boolean(process.env.IMPORT_TOOL_SECRET);
    const hasCreds = Boolean(process.env.IMPORT_ADMIN_EMAIL && process.env.IMPORT_ADMIN_PASSWORD);
    if (!hasSecret && !hasCreds) {
      fail(
        'Set IMPORT_TOOL_SECRET (preferred) or both IMPORT_ADMIN_EMAIL/IMPORT_ADMIN_PASSWORD, via ' +
        'scripts/.env.production or your own exported env vars, for --target production. Refusing to ' +
        'fall back to dev-seed defaults, and refusing to prompt interactively.',
      );
    }
    // IMPORT_ADMIN_EMAIL is also required even in the secret path — it's
    // how apps/api's 'importTool' scheme knows which ADMIN user to attach
    // (see tsoaAuth.ts). Only the password becomes unnecessary.
    if (hasSecret && !process.env.IMPORT_ADMIN_EMAIL) {
      fail('IMPORT_ADMIN_EMAIL is also required with IMPORT_TOOL_SECRET — it selects which ADMIN user apps/api attaches to the request.');
    }
  }
  return {
    IMPORT_API_URL: apiUrl,
    IMPORT_ADMIN_EMAIL: process.env.IMPORT_ADMIN_EMAIL ?? '',
    IMPORT_ADMIN_PASSWORD: process.env.IMPORT_ADMIN_PASSWORD ?? '',
    IMPORT_TOOL_SECRET: process.env.IMPORT_TOOL_SECRET ?? '',
  };
}

// NOT 5555 — that's the Android emulator's default ADB port (confirmed the
// hard way: a running emulator's qemu-system process was squatting on it,
// causing ExitOnForwardFailure to correctly-but-confusingly refuse to
// start). Pick something unlikely to collide with anything else you run.
const TUNNEL_PORT = 15432;
const REMOTE_PG_PORT = 5432;
// Not required in scripts/.env.production — these default to the real
// droplet, overridable only if you ever need to point at a different host
// (a second environment, a jump box, etc). The script spawns `ssh` exactly
// as you'd type it by hand, so it inherits the same key/agent resolution
// your own interactive `ssh deploy@143.110.191.248` already uses — no
// separate key configuration needed.
const DROPLET_SSH_HOST = process.env.DROPLET_SSH_HOST ?? '143.110.191.248';
const DROPLET_SSH_USER = process.env.DROPLET_SSH_USER ?? 'deploy';

// A bare TCP-connect check isn't reliable — it passes for ANY service
// listening on that port, tunnel or not (found the hard way: something
// unrelated was already listening on 5555 on this machine, giving a false
// "tunnel is open" positive). Actually probe Postgres itself, through the
// real DATABASE_URL the import steps will use, via a short-lived Prisma
// connection from apps/api's own installed @prisma/client.
function probeDatabaseUrl(url: string, cwd: string): Promise<{ ok: boolean; error: string }> {
  return new Promise((resolve) => {
    const code = `
      const { PrismaClient } = require('@prisma/client');
      const prisma = new PrismaClient({ datasources: { db: { url: ${JSON.stringify(url)} } } });
      prisma.$queryRaw\`SELECT 1\`
        .then(() => { process.stdout.write('PROBE_OK'); process.exit(0); })
        .catch((e) => { process.stderr.write(String(e && e.message || e).split('\\n')[0]); process.exit(1); })
        .finally(() => prisma.$disconnect());
    `;
    const probe = spawn('node', ['-e', code], { cwd, timeout: 6000 });
    let err = '';
    probe.stderr?.on('data', (d) => { err += d.toString(); });
    probe.on('close', (exitCode) => resolve({ ok: exitCode === 0, error: err.trim() }));
    probe.on('error', (e) => resolve({ ok: false, error: String(e) }));
  });
}

// ── Self-managed SSH tunnel ─────────────────────────────────────────────
// Production Postgres publishes no port by design. Rather than making you
// open/close an SSH tunnel by hand in a separate terminal every run, the
// script spawns and owns one itself for the lifetime of this process:
// opened here (only when a direct-DB step actually needs it), closed in
// main()'s finally / the signal handlers below — success, failure, or
// Ctrl+C all clean it up the same way.

let tunnelChild: ReturnType<typeof spawn> | null = null;

function stopTunnel(): void {
  if (!tunnelChild) return;
  console.log('\n▶ closing SSH tunnel');
  tunnelChild.kill('SIGTERM');
  tunnelChild = null;
}
process.on('SIGINT', () => { stopTunnel(); process.exit(130); });
process.on('SIGTERM', () => { stopTunnel(); process.exit(143); });

async function startTunnel(): Promise<void> {
  console.log(`\n▶ opening SSH tunnel: 127.0.0.1:${TUNNEL_PORT} -> ${DROPLET_SSH_USER}@${DROPLET_SSH_HOST}:${REMOTE_PG_PORT}`);
  const child = spawn(
    'ssh',
    [
      '-N', // just forward ports, don't run a remote command
      '-L', `${TUNNEL_PORT}:127.0.0.1:${REMOTE_PG_PORT}`,
      // Refuse to start rather than silently succeed if the LOCAL port is
      // already taken by something else (exactly the false-positive this
      // script's own probeDatabaseUrl comment above was written to catch) —
      // surfaces as a clear, named stderr line instead of a silent no-op.
      '-o', 'ExitOnForwardFailure=yes',
      // Non-interactive: fail fast instead of hanging on a password/passphrase
      // prompt this script has no way to answer.
      '-o', 'BatchMode=yes',
      '-o', 'StrictHostKeyChecking=accept-new',
      `${DROPLET_SSH_USER}@${DROPLET_SSH_HOST}`,
    ],
    { stdio: ['ignore', 'ignore', 'pipe'] },
  );
  tunnelChild = child;

  let earlyExit: { code: number | null; stderr: string } | null = null;
  let stderrBuf = '';
  child.stderr?.on('data', (d) => { stderrBuf += d.toString(); });
  child.on('exit', (code) => { if (earlyExit === null) earlyExit = { code, stderr: stderrBuf }; });
  child.on('error', (e) => { if (earlyExit === null) earlyExit = { code: null, stderr: String(e) }; });

  // Poll with the real Postgres probe (see probeDatabaseUrl above — a bare
  // "is the port open" check isn't trustworthy), bailing out immediately if
  // ssh itself already exited (bad host, rejected key, port already in use).
  const deadline = Date.now() + 10_000;
  while (Date.now() < deadline) {
    if (earlyExit) {
      throw new Error(`SSH tunnel exited before coming up (code ${earlyExit.code}): ${earlyExit.stderr.trim() || '(no stderr — check `ssh -v` by hand if this recurs)'}`);
    }
    const probe = await probeDatabaseUrl(process.env.PRODUCTION_DATABASE_URL as string, API_DIR);
    if (probe.ok) {
      console.log('  tunnel up, Postgres reachable');
      return;
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error('Tunnel did not come up (or Postgres stayed unreachable through it) within 10s.');
}

async function resolveDbEnv(target: Target): Promise<Record<string, string>> {
  if (target === 'local') {
    // Direct-DB child scripts each load apps/api/.env themselves
    // (`import 'dotenv/config'` run with cwd: apps/api) — nothing to
    // override here, that's already correct.
    return {};
  }
  if (!process.env.PRODUCTION_DATABASE_URL) {
    fail(
      'PRODUCTION_DATABASE_URL is not set. Set it in scripts/.env.production, pointed at the tunnel\'s ' +
      `local port, e.g.: postgresql://sypher:<real-password>@127.0.0.1:${TUNNEL_PORT}/sypher_next`,
    );
  }
  await startTunnel(); // throws on failure — caught by main()'s top-level catch, which also cleans up
  return { DATABASE_URL: process.env.PRODUCTION_DATABASE_URL };
}

// ── Step runner ───────────────────────────────────────────────────────────

interface StepResult {
  name: string;
  status: 'ran' | 'skipped' | 'not-reached' | 'failed';
  ms?: number;
  stderrTail?: string;
}

// Quote each token ourselves and hand spawn() ONE pre-built command string
// (empty args array) — shell:true with a non-empty args array makes Node
// print a DEP0190 warning because it can't guarantee it escaped everything
// safely; building and quoting the string ourselves removes the ambiguity
// instead of just suppressing the warning.
function quoteArg(arg: string): string {
  if (/^[A-Za-z0-9_\-./:]+$/.test(arg)) return arg;
  return `"${arg.replace(/(["\\$`])/g, '\\$1')}"`;
}

function runChild(cmd: string, args: string[], cwd: string, extraEnv: Record<string, string>): Promise<{ code: number; stderrTail: string }> {
  const fullCommand = [cmd, ...args].map(quoteArg).join(' ');
  return new Promise((resolve) => {
    const child = spawn(fullCommand, [], {
      cwd,
      env: { ...process.env, ...extraEnv },
      shell: true, // resolves npx/node consistently across Windows/PowerShell and POSIX shells
      stdio: ['inherit', 'inherit', 'pipe'],
    });
    let stderrBuf = '';
    child.stderr?.on('data', (chunk) => {
      const text = chunk.toString();
      process.stderr.write(text);
      stderrBuf = (stderrBuf + text).slice(-4000); // keep last ~4000 chars for the summary
    });
    child.on('close', (code) => resolve({ code: code ?? 1, stderrTail: stderrBuf.trim() }));
  });
}

async function runStep(
  results: StepResult[],
  name: string,
  scriptPathForGuard: string,
  target: Target,
  run: () => Promise<{ code: number; stderrTail: string }>,
): Promise<boolean> {
  assertNotForbidden(target, scriptPathForGuard);
  console.log(`\n▶ ${name}`);
  const started = Date.now();
  const { code, stderrTail } = await run();
  const ms = Date.now() - started;
  if (code !== 0) {
    results.push({ name, status: 'failed', ms, stderrTail });
    return false;
  }
  results.push({ name, status: 'ran', ms });
  return true;
}

function printSummary(results: StepResult[]) {
  console.log('\n' + '─'.repeat(60));
  console.log('SUMMARY');
  console.log('─'.repeat(60));
  for (const r of results) {
    const icon = r.status === 'ran' ? '✅' : r.status === 'skipped' ? '⏭ ' : r.status === 'failed' ? '🛑' : '⏹ ';
    const time = r.ms != null ? ` (${(r.ms / 1000).toFixed(1)}s)` : '';
    console.log(`${icon} ${r.name}${time}`);
    if (r.status === 'failed' && r.stderrTail) {
      console.log('   stderr tail:');
      for (const line of r.stderrTail.split('\n').slice(-15)) console.log(`     ${line}`);
    }
  }
  console.log('─'.repeat(60));
}

// ── Inline verify step (replaces the non-general check-course-import.mjs) ─

async function verifyCourses(apiUrl: string, adminEmail: string, adminPassword: string, importToolSecret: string, slugsToCheck: string[]) {
  console.log(`\n▶ verify: course catalog via ${apiUrl}`);
  let authHeaders: Record<string, string>;
  if (importToolSecret) {
    authHeaders = { 'X-Import-Tool-Secret': importToolSecret };
  } else {
    const login = await fetch(`${apiUrl}/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: adminEmail, password: adminPassword }),
    });
    if (!login.ok) throw new Error(`verify: login failed, HTTP ${login.status}`);
    const cookie = login.headers.getSetCookie().map((c) => c.split(';')[0]).join('; ');
    authHeaders = { Cookie: cookie };
  }
  const catalog: { total: number; courses: { slug: string; id: string; status: string }[] } = await fetch(
    `${apiUrl}/courses/manage/list?limit=200`,
    { headers: authHeaders },
  ).then((r) => {
    if (!r.ok) throw new Error(`verify: catalog fetch failed, HTTP ${r.status}`);
    return r.json();
  });
  console.log(`  catalog total: ${catalog.total}`);
  for (const slug of slugsToCheck) {
    const course = catalog.courses.find((c) => c.slug === slug);
    if (!course) {
      console.log(`  ${slug}: NOT FOUND`);
      continue;
    }
    const modules: unknown[] = await fetch(`${apiUrl}/courses/${course.id}/manage/modules`, { headers: authHeaders }).then((r) => r.json());
    console.log(`  ${slug}: status=${course.status} modules=${modules.length}`);
  }
}

// ── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const { target } = args;

  if (target === 'production') loadProductionEnvFile();

  const runCourses = args.all || args.courses !== null;
  const runCodingProblems = args.all || args.codingProblems;
  const runMockExams = args.all || args.mockExams;
  const needsDb = runCodingProblems || runMockExams;

  const httpEnv = runCourses || args.all ? resolveHttpEnv(target) : {};
  const dbEnv = needsDb ? await resolveDbEnv(target) : {};

  console.log(`Publishing content — target: ${target}`);
  if (target === 'production') {
    console.log(`  IMPORT_API_URL=${httpEnv.IMPORT_API_URL ?? '(not needed this run)'}`);
    console.log(needsDb ? `  DATABASE_URL: production, via tunnel on :${TUNNEL_PORT}` : '  (no direct-DB steps this run)');
  }

  const results: StepResult[] = [];
  let ok = true;

  // 1) Courses (Docusaurus-sourced, via import-docusaurus-course.ts)
  if (ok && runCourses) {
    const slugs = args.courses ?? []; // empty = script's own "all target courses" default
    if (args.all && !args.courses) {
      console.log(
        '\nNOTE: --all imports every course in import-docusaurus-course.ts\'s TARGET_COURSES list, ' +
        'including "coding-bootcamp" — its own header comment flags a known Judge0/Supabase-auth gap ' +
        'for that one. Low-risk either way: imported courses always land as status: draft (never ' +
        'auto-published), so this cannot expose an unfinished course to real users by itself.',
      );
    }
    ok = await runStep(results, `courses: import-docusaurus-course.ts ${slugs.join(' ') || '(all target courses)'}`, 'import-docusaurus-course.ts', target, () =>
      runChild('npx', ['tsx', 'scripts/import-docusaurus-course.ts', ...slugs], API_DIR, httpEnv),
    );
  } else if (!runCourses) {
    results.push({ name: 'courses: import-docusaurus-course.ts', status: 'skipped' });
  }

  // 2) Coding problems: seed + the 5 fixups, in dependency order
  if (ok && runCodingProblems) {
    ok = await runStep(results, 'coding problems: seed-coding-problems.ts', 'seed-coding-problems.ts', target, () =>
      runChild('npx', ['tsx', 'scripts/seed-coding-problems.ts'], API_DIR, dbEnv),
    );
    const fixups = [
      'fixup-coding-problem-solutions-shared.ts',
      'fixup-coding-problem-remove-code-heading.ts',
      'fixup-coding-problem-remove-back-link.ts',
      'fixup-coding-problem-example-headings.ts',
      'fixup-coding-problem-spec-headings.ts',
    ];
    for (const fixup of fixups) {
      if (!ok) break;
      ok = await runStep(results, `coding problems: ${fixup}`, fixup, target, () =>
        runChild('npx', ['tsx', `scripts/${fixup}`], API_DIR, dbEnv),
      );
    }
  } else if (!runCodingProblems) {
    results.push({ name: 'coding problems: seed + fixups', status: 'skipped' });
  }

  // 3) Mock exam banks
  if (ok && runMockExams) {
    ok = await runStep(results, 'mock exams: import-mock-exams.mjs', 'import-mock-exams.mjs', target, () =>
      runChild('node', ['scripts/import-mock-exams.mjs'], API_DIR, dbEnv),
    );
  } else if (!runMockExams) {
    results.push({ name: 'mock exams: import-mock-exams.mjs', status: 'skipped' });
  }

  // 4) Verify (read-only, --all only, always last)
  if (ok && args.all) {
    try {
      const slugsToVerify = args.courses ?? []; // nothing course-specific known for a full --all sweep beyond the catalog total
      await verifyCourses(httpEnv.IMPORT_API_URL, httpEnv.IMPORT_ADMIN_EMAIL, httpEnv.IMPORT_ADMIN_PASSWORD, httpEnv.IMPORT_TOOL_SECRET, slugsToVerify);
      results.push({ name: 'verify: course catalog', status: 'ran' });
    } catch (err) {
      ok = false;
      results.push({ name: 'verify: course catalog', status: 'failed', stderrTail: String((err as Error).message || err) });
    }
  } else if (args.all) {
    results.push({ name: 'verify: course catalog', status: 'not-reached' });
  }

  printSummary(results);
  return ok ? 0 : 1;
}

// Not `try { ... process.exit() } finally { stopTunnel() }` inside main()
// itself — process.exit() forces immediate termination and Node does not
// reliably run a pending finally block first. Cleanup lives here instead,
// after main()'s promise has actually settled, so it always runs exactly
// once regardless of which path (return, throw, or a fail() call earlier
// in the flow) got us here.
main()
  .then((code) => {
    stopTunnel();
    process.exit(code);
  })
  .catch((err) => {
    stopTunnel();
    console.error('\nFATAL:', err instanceof Error ? err.message : err);
    process.exit(1);
  });
