import json, os
BANK = "apps/web/question-bank"
EXAM = "istqb-ct-genai"
PRE = "ISTQB-CTGENAI-MED"
EZ = os.path.join(BANK, EXAM, "medium.json")
EX = os.path.join(BANK, EXAM, "medium_extra.json")
meta = json.load(open(EZ, encoding="utf-8"))
Q = []
N = 56
def q(dom, ques, a, b, c, d, ans, exp):
    global N
    Q.append({"id": f"{PRE}-{N:04d}", "difficulty": "medium", "type": "MCQ", "domain": dom, "question": ques, "options": {"A": a, "B": b, "C": c, "D": d}, "correct_answer": [ans], "explanation": exp})
    N += 1
q("GenAI Foundations for Testers", "Why does sampling temperature break exact-match testing?", "Outputs vary stochastically per run", "Models never vary", "Tests fill time", "Temperature fixes outputs", "A", "Sampling randomness demands statistical oracles.")
q("GenAI Foundations for Testers", "RAG answers contradict the KB; where to look first?", "Retrieval precision versus generation faithfulness", "Font rendering", "Network cables", "Billing configs", "A", "Split evals isolate the stage.")
q("GenAI Foundations for Testers", "What makes an oracle problem in GenAI?", "No single correct answer exists", "Oracle is a database", "Answers are always right", "Tests are free", "A", "Open-ended outputs need rubrics or references.")
q("GenAI Foundations for Testers", "Why pin model versions in tests?", "Upgrades silently shift behavior", "Versions never change", "Pinning slows apps", "Testing wastes time", "A", "Version pins stabilize comparisons.")
q("GenAI Foundations for Testers", "What does an LLM-as-judge need before trust?", "Calibration against human labels", "Bigger prompts only", "No calibration", "Judges are perfect", "A", "Judge agreement must be measured.")
q("Quality Attributes for GenAI", "Which attribute set covers a summarizer?", "Accuracy, coverage, conciseness, tone", "Only speed", "Only cost", "Only size", "A", "Multi-attribute evals match the task.")
q("Quality Attributes for GenAI", "Toxicity passes in English but not German; what failed?", "Multilingual safety coverage", "English is safest", "Translation banned", "Nothing failed", "A", "Cross-language red-teaming is required.")
q("Quality Attributes for GenAI", "Why measure faithfulness in RAG?", "Answers must stick to sources", "Faithfulness fills dashboards", "Answers never stray", "Sources never matter", "A", "Faithfulness curbs invention.")
q("Test Design for Non-Determinism", "How to reduce flaky GenAI tests?", "Lower temperature plus aggregate runs", "Raise temperature", "Single run decisions", "Ignore failures", "A", "Determinism plus statistics tame flake.")
q("Test Design for Non-Determinism", "What is a good pass criterion for open-ended answers?", "Rubric threshold across N samples", "Exact match only", "Never pass", "Random choice", "A", "Rubrics plus sampling scale.")
q("Evaluation Methods and Metrics", "Why track pass@k for code generation?", "Measures success within attempts", "K fills math", "Only pass@1 matters", "Metrics never help", "A", "Practical success spans retries.")
q("Evaluation Methods and Metrics", "What guards against reference-set overfitting?", "Hold-out eval sets refreshed regularly", "Reuse one set forever", "Skip evals", "Train on evals", "A", "Fresh hold-outs keep honesty.")
q("Data and Environment Management", "Why isolate per-tenant test data?", "Prevent cross-tenant leakage", "Isolation fills disks", "Tenants never mix", "Sharing safer", "A", "Tenancy isolation is compliance-critical.")
q("Automation and CI/CD", "Why budget GenAI eval runs in CI?", "Token costs can explode", "Budgets fill sheets", "Tokens are free", "CI never costs", "A", "Cost caps keep CI sane.")
q("Automation and CI/CD", "What gates a GenAI release?", "Eval thresholds on quality and safety", "Nothing", "Gut feeling", "Only speed", "A", "Threshold gates block regressions.")
q("Risk, Ethics, and Governance", "PII found in prompt logs; what first?", "Redaction pipeline plus log purge", "Ignore PII", "Log more", "Delete dashboards", "A", "Scrubbing protects privacy.")
q("Risk, Ethics, and Governance", "Why document GenAI limitations?", "Users deserve known bounds", "Docs fill wikis", "Models are perfect", "Limits never matter", "A", "Transparency manages expectations.")
q("GenAI Foundations for Testers", "Why test structured output edge cases?", "Malformed JSON crashes apps", "JSON never breaks", "Schema optional", "Parsing always works", "A", "Boundary tests prevent crashes.")
q("Risk, Ethics, and Governance", "What is model jailbreak risk in prod?", "Policy bypass via crafted inputs", "Prisons for models", "Hardware failure", "Version drift", "A", "Adversarial prompts bypass guards.")
q("Evaluation Methods and Metrics", "Why slice quality metrics by segment?", "Averages hide subgroup failures", "Slices fill charts", "One score covers all", "Slicing slows evals", "A", "Slices expose disparity.")
q("Test Design for Non-Determinism", "How to compare two models fairly?", "Same prompts, seeds, rubric across both", "Different prompts each", "Gut comparison", "Skip fairness", "A", "Controlled comparisons are valid.")
q("Data and Environment Management", "Why freeze eval prompts and data per release?", "Reproducible regression baselines", "Freezing fills disks", "Data never changes", "Baselines optional", "A", "Frozen sets enable diffing.")
q("Automation and CI/CD", "Why smoke-test after model upgrade?", "Fast catch of breakage", "Smoke fills logs", "Upgrades never break", "Testing optional", "A", "Quick gates catch issues.")
q("GenAI Foundations for Testers", "What is prompt leakage testing?", "Ensure system prompts stay hidden", "Leak tests fill logs", "Prompts are public", "Leakage harmless", "A", "Egress checks protect IP.")
q("Quality Attributes for GenAI", "Why test coherence on long outputs?", "Long generations drift logically", "Long is always fine", "Coherence never drifts", "Tests optional", "A", "Length stress reveals drift.")
q("Risk, Ethics, and Governance", "Why log refusals with reasons?", "Appeals need explanations", "Logs fill disks", "Refusals self-explain", "Reasons optional", "A", "Reasoned blocks build trust.")
q("Evaluation Methods and Metrics", "What is inter-rater reliability for human evals?", "Agreement measure across raters", "Rater speed", "Rater count only", "Reliability myth", "A", "Agreement validates labels.")
q("Automation and CI/CD", "Why snapshot outputs on known prompts?", "Diff detection of regressions", "Snapshots fill disks", "Outputs never change", "Snapshots optional", "A", "Golden outputs catch drift.")
q("Test Design for Non-Determinism", "Why test empty and oversized inputs?", "Edge cases crash pipelines", "Edges fill tests", "Inputs never edge", "Pipeline is robust", "A", "Boundaries expose failures.")
q("Quality Attributes for GenAI", "Why measure latency percentiles?", "Tails drive user experience", "Averages suffice", "Latency never varies", "Percentiles optional", "A", "p95 plus p99 set SLOs.")
q("Evaluation Methods and Metrics", "Why blind the judge to model name?", "Prevent brand bias", "Blinding fills forms", "Judges are neutral", "Names never bias", "A", "Blind scoring is fair.")
q("Data and Environment Management", "Why version guardrail configs?", "Roll back bad policy fast", "Versioning fills repos", "Policy never changes", "Versioning optional", "A", "Config versioning enables control.")
q("Risk, Ethics, and Governance", "What is a human-in-the-loop gate?", "Mandatory review before risky actions", "An optional checkbox", "A CI stage", "A meeting", "A", "Gates contain high-stakes risk.")
q("Test Design for Non-Determinism", "Why fix random seeds where possible?", "Reproducibility of failures", "Seeds fill gardens", "Random is better", "Seeds optional", "A", "Determinism aids debugging.")
q("GenAI Foundations for Testers", "Why test embedding drift?", "Vector space shifts break retrieval", "Embeddings never drift", "Drift fills dashboards", "Drift harmless", "A", "Drift alarms protect recall.")
q("Quality Attributes for GenAI", "Why test completion truncation?", "Cut outputs hide conclusions", "Truncation never happens", "Tests optional", "Length always enough", "A", "Stop reasons matter.")
q("Evaluation Methods and Metrics", "Why use pairwise comparisons?", "Relative preference scales better", "Pairwise fills time", "Absolute only", "Comparisons bias-free", "A", "Pairwise suits open-ended quality.")
q("Data and Environment Management", "Why rotate synthetic test users?", "Prevent profile overfitting", "Users fill DBs", "One user suffices", "Rotation optional", "A", "Diverse personas widen coverage.")
q("Automation and CI/CD", "Why fail builds on safety regressions?", "Safety is a release blocker", "Safety optional", "Builds never fail", "Safety later", "A", "Gates protect users.")
q("Test Design for Non-Determinism", "What is acceptance sampling here?", "N-run pass-rate thresholds", "Accept any sample", "Sampling free", "No thresholds", "A", "Statistical acceptance scales.")
q("Risk, Ethics, and Governance", "Why align guardrails to policy docs?", "Consistency between rules and code", "Alignment fills decks", "Policy never matters", "Guards self-write", "A", "Traceability proves intent.")
q("GenAI Foundations for Testers", "Why test function-calling edge cases?", "Malformed calls break flows", "Calls never fail", "Schemas optional", "Edge cases rare", "A", "Typed boundaries need tests.")
q("Quality Attributes for GenAI", "Why measure answer completeness?", "Partial answers mislead users", "Completeness fills rubrics", "Answers always full", "Metric optional", "A", "Coverage checks prevent gaps.")
q("Evaluation Methods and Metrics", "Why hold out adversarial sets?", "Robustness needs unseen attacks", "Sets fill disks", "Attacks never vary", "Holdouts optional", "A", "Unseen attacks test true robustness.")
q("Data and Environment Management", "Why separate eval and prod endpoints?", "Isolate traffic and metrics", "Separation fills configs", "One endpoint fits all", "Separation slows deploys", "A", "Isolation keeps signals clean.")
out = {"exam_name": meta["exam_name"], "exam_code": meta["exam_code"], "duration_minutes": meta["duration_minutes"], "live_exam_question_count": meta["live_exam_question_count"], "difficulty_tier": "medium", "questions_in_this_file": len(Q), "target_for_tier": 100, "last_updated": "2026", "questions": Q}
json.dump(out, open(EX, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"WROTE {EX} questions={len(Q)}")