const courses = [
  {
    slug: 'python-for-ai-engineers',
    icon: '🐍',
    title: 'Python for AI Engineers',
    tag: 'Flagship',
    difficulty: 'Beginner → Advanced',
    hours: '50–70h',
    description: 'A complete, job-ready Python course designed for engineers who want to build AI applications — from your first script to production-grade AI pipelines.',
    longDesc: 'Every lesson follows the same four-part format: you learn the concept, build something real with it, avoid the common mistakes, and then test what you have learned. Code is never shown unexplained — every example is annotated, production-quality, and progressive.',
    hook: "Go from your first print() to shipping production AI pipelines.",
    outcomes: [
      'Write clean, idiomatic Python from day one',
      'Work confidently with NumPy, Pandas, and real data',
      'Call LLM APIs and build your first RAG pipeline',
      'Ship code with tests, Docker, and CI/CD like a pro',
    ],
    gradient: 'linear-gradient(135deg, #1E4D8C 0%, #357ABD 100%)',
    topics: ['Python', 'NumPy', 'Pandas', 'FastAPI', 'LLMs', 'Testing'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Section 1 — Python Foundations', topics: ['Setup', 'First Program', 'Virtual Environments', 'Variables', 'Strings', 'Lists', 'Tuples', 'Dictionaries', 'Sets', 'Control Flow', 'Loops'] },
      { label: 'Section 2 — Functions & Modular Code', topics: ['Functions', 'Modules', 'File Handling', 'Comprehensions', 'Generators', 'Decorators', 'Context Managers'] },
      { label: 'Section 3 — Professional Python', topics: ['Error Handling', 'Dataclasses', 'Type Hints', 'Logging'] },
      { label: 'Section 4 — Object-Oriented Python', topics: ['Classes', 'Inheritance', 'Composition', 'Magic Methods'] },
      { label: 'Section 5 — Data & Analytics', topics: ['NumPy', 'Pandas', 'Data Visualization', 'JSON', 'CSV'] },
      { label: 'Section 6 — APIs & Async', topics: ['Requests', 'HTTPX', 'API Authentication', 'Async Python'] },
      { label: 'Section 7 — AI Engineering', topics: ['LLM API Basics', 'Prompt Engineering', 'Structured Output', 'Embeddings', 'RAG', 'AI Pipelines'] },
      { label: 'Section 8 — Dev Tools', topics: ['Pytest', 'Docker', 'CI/CD', 'Packaging'] },
      { label: 'Section 9 — Production Skills', topics: ['Project Structure', 'Clean Code', 'Performance'] },
      { label: 'Practice', topics: ['Beginner Exercises', 'Intermediate Exercises', 'Advanced Exercises', 'Solutions'] },
    ],
  },
  {
    slug: 'agentic-ai-fundamentals',
    icon: '🤖',
    title: 'Agentic AI Fundamentals',
    tag: 'Trending',
    difficulty: 'Intermediate → Advanced',
    hours: '45–60h',
    description: 'Bridge the gap between prompt engineering and autonomous agents. Build memory, tools, planning loops, multi-agent systems, and production MCP servers.',
    longDesc: 'Start by understanding what agents are and how they differ from chatbots and deterministic workflows. From there build each component of an agent system — memory, tools, planning, execution loops — until you have a complete working agent architecture.',
    hook: 'Stop prompting. Start building agents that plan, act, and recover.',
    outcomes: [
      'Design agent memory, tools, and planning loops from scratch',
      'Build multi-agent systems that coordinate and hand off work',
      'Wire up MCP servers your agents can actually use',
      'Evaluate, guard, and ship agents that survive production',
    ],
    gradient: 'linear-gradient(135deg, #6A1B9A 0%, #9C27B0 100%)',
    topics: ['Agents', 'MCP', 'Tool Use', 'Planning', 'Guardrails'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Section 1 — Foundations', topics: ['What Is AI Engineering?', 'LLM Fundamentals', 'Tokens and Context Windows', 'Prompt Engineering Basics', 'LLM APIs in Practice'] },
      { label: 'Section 2 — Prompt Engineering Deep Dive', topics: ['System Prompts', 'Prompt Patterns', 'Few-Shot Prompting', 'Chain of Thought & Reasoning', 'Prompt Templates', 'Structured Output Prompting', 'Prompt Testing & Iteration'] },
      { label: 'Section 3 — Agent Architecture', topics: ['What Is an Agent?', 'Agent vs Chatbot vs Workflow', 'Anatomy of an Agent', 'Reasoning vs Execution', 'Agent Memory', 'Agent Tools & Tool Calling', 'Planning & Decision Making'] },
      { label: 'Section 4 — Agent Loops', topics: ['Observe-Think-Act Loop', 'ReAct Pattern', 'Plan and Execute', 'Reflection & Self-Correction', 'Loop Safety & Recovery', 'Human in the Loop'] },
      { label: 'Section 5 — Multi-Agent Systems', topics: ['Orchestrator & Supervisor Patterns', 'Specialist Agents', 'Agent Communication & Coordination', 'Shared Memory & State', 'When to Use Multi-Agent'] },
      { label: 'Section 6 — MCP', topics: ['What Is MCP?', 'MCP Architecture', 'MCP Primitives', 'Transports', 'Building an MCP Server', 'Building an MCP Client', 'MCP with Claude Code'] },
      { label: 'Section 7 — Evaluation & Safety', topics: ['Evaluating Agents', 'Trajectory Evaluation', 'Tool Evaluation', 'Prompt Injection & Guardrails', 'Observability & Tracing', 'Cost & Latency Tracking'] },
      { label: 'Section 8 — Production', topics: ['Deployment Patterns', 'Versioning Prompts & Tools', 'Configuration Management', 'Authentication', 'Scaling Agent Systems', 'Caching & Retries', 'Monitoring Production Agents'] },
    ],
  },
  {
    slug: 'system-design-fundamentals',
    icon: '🏗️',
    title: 'System Design Fundamentals',
    tag: 'Popular',
    difficulty: 'Intermediate',
    hours: '35–50h',
    description: 'FAANG-level guide to system design — from foundations to advanced distributed systems patterns. Learn to design systems that scale to billions of users.',
    longDesc: 'A comprehensive, FAANG-level guide to system design. Each topic covers mental models, deep dives, architecture tradeoffs, real-world case studies, and interview practice with a challenge section.',
    hook: 'Design systems that scale to millions — and explain why.',
    outcomes: [
      'Master the building blocks: load balancers, caches, queues, CDNs',
      'Reason through CAP, consistent hashing, and replication tradeoffs',
      'Walk through real architectures: Instagram, Uber, Netflix, and more',
      'Handle the system design interview with confidence',
    ],
    gradient: 'linear-gradient(135deg, #E65100 0%, #FF8F00 100%)',
    topics: ['Scalability', 'Databases', 'Microservices', 'Patterns'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Section 1 — Foundations of System Design', topics: ['What Is System Design?', 'Why System Design Matters', 'Functional vs Non-Functional Requirements', 'Scalability', 'Availability', 'Reliability', 'Durability', 'Consistency', 'Latency vs Throughput', 'Capacity Estimation', 'System Design Process'] },
      { label: 'Section 2 — Core Building Blocks', topics: ['Load Balancing', 'Caching', 'Databases', 'CDNs', 'DNS', 'API Design', 'Proxies', 'Message Queues'] },
      { label: 'Section 3 — Distributed Systems Concepts', topics: ['Consistent Hashing', 'Data Partitioning', 'Replication', 'CAP Theorem', 'PACELC', 'Gossip Protocol', 'Quorum', 'Leader Election'] },
      { label: 'Section 4 — Design Patterns', topics: ['Microservices', 'Event-Driven Architecture', 'CQRS', 'Saga Pattern', 'Strangler Fig', 'Circuit Breaker', 'Bulkhead'] },
      { label: 'Section 5 — Real-World Case Studies', topics: ['URL Shortener', 'Instagram', 'Twitter', 'Uber', 'Dropbox', 'Netflix', 'YouTube', 'WhatsApp'] },
    ],
  },
  {
    slug: 'git-github-actions',
    icon: '🔀',
    title: 'Git & GitHub Actions',
    tag: 'Essential',
    difficulty: 'Beginner → Advanced',
    hours: '30–42h',
    description: 'Version control from first commit to production CI/CD. Master branching strategies, collaboration workflows, and automated deployment pipelines.',
    longDesc: 'This course teaches Git from the ground up — from your first commit to production CI/CD pipelines. You will learn version control fundamentals, branching strategies, collaboration workflows, and GitHub Actions for automated testing and deployment.',
    hook: 'Version control and CI/CD, from your first commit to production releases.',
    outcomes: [
      'Branch, merge, and resolve conflicts without fear',
      'Collaborate cleanly with pull requests and code review',
      'Automate testing and deployment with GitHub Actions',
      'Build CI/CD pipelines that gate quality, not just ship code',
    ],
    gradient: 'linear-gradient(135deg, #1A237E 0%, #3949AB 100%)',
    topics: ['Git', 'GitHub', 'CI/CD', 'Actions', 'Deployment'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Getting Started', topics: ['What Version Control Is', 'Using the Terminal', 'Installing & Configuring Git', 'Creating Your GitHub Account', 'Your First Repository'] },
      { label: 'Git Foundations', topics: ['What Is Version Control', 'Init, Add, and Commit', 'The Staging Area', 'Log and History', 'Gitignore', 'Reset, Revert, and Checkout'] },
      { label: 'Branching & Merging', topics: ['Branches', 'Merge', 'Rebase', 'Merge Conflicts', 'Cherry-Pick', 'Stash'] },
      { label: 'Collaboration', topics: ['Remote Repositories', 'Pull, Push, Fetch', 'Pull Requests', 'Code Review', 'Forking Workflow'] },
      { label: 'GitHub Actions Fundamentals', topics: ['What Is CI/CD?', 'Your First Workflow', 'Triggers & Events', 'Jobs & Steps', 'Matrix Builds'] },
      { label: 'Advanced Actions & Delivery', topics: ['Custom Actions', 'Secrets & Environment', 'Deployment Strategies', 'Release Management', 'Scheduled Workflows'] },
      { label: 'CI/CD as a Quality System', topics: ['Testing in CI', 'Linting & Formatting', 'Security Scanning', 'Artifact Management', 'Status Checks & Gates'] },
    ],
  },
  {
    slug: 'ai-engineering-crash-course',
    docsSlug: 'ai-engineering-hands-on',
    icon: '⚡',
    title: 'AI Engineering Crash Course',
    tag: 'Hands-On',
    difficulty: 'Intermediate → Advanced',
    hours: '35–50h',
    description: 'Build real AI applications fast — from your first LLM API call to a production-ready agent system. Designed for engineers who learn by doing.',
    longDesc: 'This course teaches you to build real AI applications with LLM APIs, local models, MCP servers, and autonomous agents — from your first API call to a production-ready agent system.',
    hook: 'The fastest hands-on path from an API key to a working agent.',
    outcomes: [
      'Call LLM APIs directly and handle streaming, tools, and structured output',
      'Connect to and build your own MCP servers',
      'Build a working RAG pipeline over real data',
      'Ship an agent loop that runs in production',
    ],
    gradient: 'linear-gradient(135deg, #00695C 0%, #26A69A 100%)',
    topics: ['LLMs', 'RAG', 'Agents', 'MCP', 'Deploy'],
    videoId: '1elYxgKplzY',
    modules: [
      { label: 'Getting Started', topics: ['What LLMs and APIs Actually Are', 'Installing Python & Using the Terminal', 'Environment Variables Explained', 'Using Claude Code from Day One'] },
      { label: 'Calling LLMs Directly', topics: ['Overview of LLM Providers', 'Making Your First API Call', 'System Prompts and Temperature', 'Streaming Responses', 'Multimodal Inputs', 'Structured Outputs with Pydantic', 'Tool Calling and Function Calling'] },
      { label: 'Building with MCP Servers', topics: ['What MCP Actually Is', 'Connecting to Existing MCP Servers', 'Exposing Tools via MCP', 'Building a Custom MCP Server'] },
      { label: 'RAG & Data', topics: ['What Embeddings Are', 'Vector Databases', 'Building a RAG Pipeline', 'Chunking Strategies', 'Hybrid Search'] },
      { label: 'Agent Patterns', topics: ['Building an Agent Loop', 'ReAct in Practice', 'Multi-Agent Systems', 'Agent Evaluation'] },
      { label: 'Production & Deployment', topics: ['Observability', 'Prompt Management', 'Caching', 'Error Handling'] },
      { label: 'Capstone', topics: ['End-to-End AI Application'] },
    ],
  },
  {
    slug: 'build-with-ai',
    icon: '🛠️',
    title: 'Build with AI',
    tag: 'Project-Based',
    difficulty: 'All Levels',
    hours: '50–80h',
    description: '20+ real-world AI projects organized by complexity — from quick mini apps to production-grade systems and portfolio-worthy platforms.',
    longDesc: 'A project-based course organized by difficulty tier. Build everything from a daily AI news digest to a multi-agent research platform, with architecture, build, and deploy phases for production projects.',
    hook: "Stop tutorial-hopping. Ship 20+ real AI projects, start to finish.",
    outcomes: [
      'Build real, working AI apps — not toy demos',
      'Progress from weekend projects to production-grade systems',
      'Learn RAG, agents, and MCP by shipping, not just reading',
      'Walk away with portfolio-ready projects you can show off',
    ],
    gradient: 'linear-gradient(135deg, #4A148C 0%, #7B1FA2 100%)',
    topics: ['10+ Projects', 'RAG', 'Agents', 'SaaS', 'MCP'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Mini Projects', topics: ['Daily AI News Digest', 'AI Movie Release Tracker', 'Job Listings Monitor', 'AI Research Paper Emailer', 'AI Recipe Finder', 'Travel Itinerary Planner', 'AI Interview Coach', 'Git Commit Message Generator', 'Pull Request Reviewer', 'README Generator'] },
      { label: 'Intermediate Projects', topics: ['Chat with PDFs', 'AI Meeting Notes Summarizer', 'AI Resume Reviewer', 'AI Customer Support Bot', 'AI Voice Notes Summarizer'] },
      { label: 'Production Projects', topics: ['Enterprise RAG System', 'AI Helpdesk', 'AI Coding Assistant', 'AI QA Engineer', 'Enterprise MCP Server', 'GitHub MCP Server', 'AI Customer Support Workflow', 'AI Ticket Routing System', 'ChatGPT Clone', 'AI Learning Platform'] },
      { label: 'Portfolio Projects', topics: ['Multi-Agent Research Platform', 'AI Testing Framework', 'AI Observability Platform', 'Enterprise Knowledge Assistant'] },
    ],
  },
  {
    slug: 'solid-principles',
    icon: '📐',
    title: 'SOLID Principles',
    tag: 'Multi-Lang',
    difficulty: 'Intermediate',
    hours: '15–20h',
    description: 'The five SOLID principles of object-oriented design implemented across JavaScript, TypeScript, Python, Java, C#, and Rust.',
    longDesc: 'Reference-style course covering the five SOLID principles of object-oriented design. Each principle has an overview page plus one implementation page per language.',
    hook: "Write object-oriented code that doesn't collapse under change.",
    outcomes: [
      'Internalize all five SOLID principles with real, not toy, examples',
      'See every principle implemented across 6 languages',
      'Recognize violations in code you already maintain',
      'Refactor fragile designs into ones that bend, not break',
    ],
    gradient: 'linear-gradient(135deg, #B71C1C 0%, #E53935 100%)',
    topics: ['SOLID', 'OOP Design', '6 Languages', 'Clean Code'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Single Responsibility', topics: ['Overview', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'Rust'] },
      { label: 'Open/Closed', topics: ['Overview', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'Rust'] },
      { label: 'Liskov Substitution', topics: ['Overview', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'Rust'] },
      { label: 'Interface Segregation', topics: ['Overview', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'Rust'] },
      { label: 'Dependency Inversion', topics: ['Overview', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'Rust'] },
    ],
  },
  {
    slug: 'design-patterns',
    icon: '🧩',
    title: 'Design Patterns',
    tag: 'Multi-Lang',
    difficulty: 'Intermediate → Advanced',
    hours: '25–35h',
    description: 'All 23 Gang-of-Four design patterns implemented across JavaScript, TypeScript, Python, Java, C#, and Rust.',
    longDesc: 'Reference-style course covering all 23 Gang-of-Four design patterns organized by creational, structural, and behavioral categories. Each pattern has a theory page plus one implementation page per language.',
    hook: 'The 23 classic design patterns, made practical again.',
    outcomes: [
      'Learn every Gang-of-Four pattern with a real-world example',
      'See each pattern implemented across 6 languages',
      "Know exactly when a pattern helps — and when it's overkill",
      'Read and review pattern-heavy code with confidence',
    ],
    gradient: 'linear-gradient(135deg, #6A1B9A 0%, #AB47BC 100%)',
    topics: ['Patterns', 'Gang of Four', '6 Languages', 'Architecture'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Creational Patterns', topics: ['Factory Method', 'Singleton', 'Abstract Factory', 'Prototype', 'Builder'] },
      { label: 'Structural Patterns', topics: ['Adapter', 'Bridge', 'Composite', 'Decorator', 'Facade', 'Flyweight', 'Proxy'] },
      { label: 'Behavioral Patterns', topics: ['Chain of Responsibility', 'Command', 'Interpreter', 'Iterator', 'Mediator', 'Memento', 'Observer', 'State', 'Strategy', 'Template Method', 'Visitor'] },
    ],
  },
  {
    slug: 'coding-bootcamp',
    icon: '💻',
    title: 'Coding Bootcamp',
    tag: 'Interview Prep',
    difficulty: 'Beginner → Advanced',
    hours: '60–90h',
    description: 'Master essential coding patterns with hundreds of LeetCode-style exercises. Each topic has easy, medium, and hard problems with detailed solutions.',
    longDesc: 'A DSA / LeetCode-style course covering 27 algorithm patterns. Each section has an index page and exercises split into Easy, Medium, and Hard with paired solutions.',
    hook: 'Crack the interview with patterns, not memorized problems.',
    outcomes: [
      'Master 27 core algorithm patterns, not one-off tricks',
      'Practice with hundreds of Easy/Medium/Hard problems',
      'Learn the pattern once, recognize it on 20 different problems',
      "Walk into interviews recognizing what you're being asked",
    ],
    gradient: 'linear-gradient(135deg, #0D47A1 0%, #1565C0 100%)',
    topics: ['Algorithms', 'Data Structures', 'LeetCode', 'Patterns'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Arrays', topics: ['Two Sum', 'Best Time to Buy Stock', 'Remove Duplicates', 'Product of Array Except Self', 'Rotate Array', 'Container With Most Water', 'Maximum Subarray', 'Merge Sorted Array'] },
      { label: 'Binary Search', topics: ['Find Minimum in Rotated', 'Search in Rotated', 'Binary Search'] },
      { label: 'DFS & BFS', topics: ['Invert Binary Tree', 'Maximum Depth', 'Same Tree', 'Level Order Traversal', 'Diameter of Tree', 'Number of Islands', 'Binary Tree Max Path Sum', 'Word Ladder'] },
      { label: 'BST', topics: ['Search in BST', 'Minimum Absolute Difference', 'Kth Smallest Element', 'Validate BST', 'Recover BST'] },
      { label: 'Backtracking', topics: ['Subsets', 'Permutations', 'Combinations', 'N-Queens'] },
      { label: 'Dynamic Programming', topics: ['Climbing Stairs', 'House Robber', 'Coin Change', 'Longest Increasing Subsequence', 'Unique Paths', 'Edit Distance', 'Word Break', 'Decode Ways'] },
      { label: 'Fast & Slow Pointers', topics: ['Middle of Linked List', 'Find Duplicate Number', 'Happy Number', 'Circular Array Loop'] },
      { label: 'Graph Algorithms', topics: ['Find Center of Star Graph', 'Keys and Rooms', 'Clone Graph', 'Max Area of Island', 'Word Ladder II'] },
      { label: 'Greedy', topics: ['Assign Cookies', 'Lemonade Change', 'Jump Game', 'Non-Overlapping Intervals', 'Partition Labels', 'Min Arrows Burst Balloons'] },
      { label: 'Bit Manipulation', topics: ['Single Number', 'Counting Bits', 'Missing Number', 'Reverse Bits', 'Sum of Two Integers'] },
      { label: 'Design', topics: ['Design HashMap', 'Min Stack', 'LRU Cache', 'Design Browser History', 'LFU Cache'] },
    ],
  },
  {
    slug: 'search-algorithms',
    icon: '🔍',
    title: 'Search Algorithms',
    tag: 'New',
    difficulty: 'Beginner → Advanced',
    hours: '12–18h',
    description: 'A reference course covering the search algorithms every engineer should know cold — from a plain linear scan to A* pathfinding.',
    longDesc: 'Each module is a single self-contained page: pseudocode, algorithm explanation, time/space complexity, and complete runnable implementations in Java, Python, TypeScript, and C#, plus 5 shared practice test cases per module.',
    hook: 'Every search algorithm you should know cold, in one sitting.',
    outcomes: [
      'Go from a plain linear scan to A* pathfinding',
      'See time/space tradeoffs made concrete, not theoretical',
      'Get runnable implementations across four languages',
      'Practice each algorithm with hands-on test cases',
    ],
    gradient: 'linear-gradient(135deg, #00838F 0%, #4DD0E1 100%)',
    topics: ['Binary Search', 'DFS', 'BFS', 'A*', 'Two-Pointer'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Search Algorithms', topics: ['Linear Search', 'Binary Search', 'Binary Search Variants', 'Ternary Search', 'Jump Search', 'Interpolation Search', 'Exponential Search', 'Depth-First Search', 'Breadth-First Search', 'A* Search', 'Two-Pointer Search Patterns', 'Search in 2D Matrix'] },
    ],
  },
  {
    slug: 'sorting-algorithms',
    icon: '🔀',
    title: 'Sorting Algorithms',
    tag: 'New',
    difficulty: 'Beginner → Advanced',
    hours: '10–15h',
    description: 'A reference course covering the sorting algorithms every engineer should know cold — from Bubble Sort to the Tim Sort hybrid powering every modern language.',
    longDesc: 'Each module is a single self-contained page: pseudocode, algorithm explanation, time/space complexity, stability, and complete runnable implementations in Python, C, C++, Java, C#, JavaScript, TypeScript, Rust, and Go, plus 5 shared practice test cases per module.',
    hook: 'From Bubble Sort to Tim Sort — know why, not just how.',
    outcomes: [
      "Understand every major sorting algorithm's tradeoffs",
      'See stability and complexity explained side by side',
      'Get runnable implementations across nine languages',
      'Know exactly which sort to reach for and why',
    ],
    gradient: 'linear-gradient(135deg, #4A148C 0%, #7B1FA2 100%)',
    topics: ['Merge Sort', 'Quick Sort', 'Heap Sort', 'Radix Sort', 'Tim Sort'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Sorting Algorithms', topics: ['Bubble Sort', 'Selection Sort', 'Insertion Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort', 'Counting Sort', 'Radix Sort', 'Bucket Sort', 'Shell Sort', 'Tim Sort', 'Comparison & Selection Guide'] },
    ],
  },
  {
    slug: 'playwright-test-automation',
    icon: '🎭',
    title: 'Playwright Test Automation',
    tag: 'New',
    difficulty: 'Beginner → Advanced',
    hours: '30–45h',
    description: 'The complete, TypeScript-only reference for Playwright — from your first locator to the 2026 AI/agentic stack (test agents, MCP, self-healing tests).',
    longDesc: 'Every module runs its examples against the same real system under test: a 4-role RBAC healthcare app with an Express API, SQLite database, and a documented — and deliberately not fully implemented — permission matrix. You test the same app from a growing number of angles as the course progresses, the way you would a real project, instead of a different disposable example every lesson.',
    hook: 'The complete TypeScript playbook for testing real applications.',
    outcomes: [
      'Test a real RBAC app end to end, not disposable demos',
      'Master locators, fixtures, and the page object model',
      'Handle auth, network mocking, and flaky async UI',
      'Get hands-on with the 2026 AI/agentic testing stack',
    ],
    gradient: 'linear-gradient(135deg, #B71C1C 0%, #EF5350 100%)',
    topics: ['Locators', 'Fixtures', 'RBAC Testing', 'CI', 'Playwright MCP'],
    videoId: 'z92nyOfBG9g',
    sut: {
      label: 'System Under Test',
      repoUrl: 'https://github.com/codedbyabhishekc/rbac-healthcare-system',
      repoName: 'codedbyabhishekc/rbac-healthcare-system',
      description: 'A 4-role RBAC healthcare app (admin / doctor / nurse / patient) with a React frontend, an Express + SQLite backend, JWT auth, and Swagger docs. Every module in this course runs its examples against it.',
      cloneCommand: 'git clone https://github.com/<your-username>/rbac-healthcare-system.git\ncd rbac-healthcare-system',
      steps: [
        'Fork the repo on GitHub first (not clone directly — the CI module later needs a repo you own), then clone your fork with the command above.',
        'Backend: cd backend && npm install && mkdir database, add a .env with PORT=5000, JWT_SECRET=<any-long-random-string>, and NODE_ENV=development, then npm start.',
        'Seed data: npm run seed — creates 3 Admins, 8 Doctors, 7 Nurses, 15 Patients, 22 Appointments, and 15 Medical Records. Default admin login: admin / admin123.',
        'Frontend: cd frontend && npm install && PORT=3002 npm start — this course pins the frontend to port 3002 permanently, not the README’s default 3000.',
        "Install Playwright: npm init playwright@latest, then set baseURL: 'http://localhost:3002' in playwright.config.ts.",
      ],
      screenshots: [
        {
          src: '/img/playwright-test-automation/rbac-login.png',
          alt: 'RBAC healthcare system login page running at localhost:3002/login, showing the demo admin credentials',
          caption: 'localhost:3002/login',
        },
        {
          src: '/img/playwright-test-automation/rbac-admin-dashboard.png',
          alt: 'RBAC healthcare system admin dashboard running at localhost:3002/dashboard, showing the seeded users table',
          caption: 'localhost:3002/dashboard — logged in as admin',
        },
      ],
      docsLink: '/docs/playwright-test-automation/setup/build-it',
    },
    modules: [
      { label: 'Getting Started', topics: ['Setup', 'Why Playwright, and How It Differs', 'Project Structure and Config'] },
      { label: 'Core Locators and Actions', topics: ['Locators', 'Actions and Web-First Assertions'] },
      { label: 'Auth and Architecture', topics: ['Authentication and Session State', 'Page Object Model', 'Fixtures'] },
      { label: 'Network and API', topics: ['Network Interception and Mocking', 'API Requests from Playwright'] },
      { label: 'RBAC and Async UI', topics: ['Testing the RBAC Permission Matrix', 'Handling Dynamic and Async UI'] },
      { label: 'Visual and Cross-Browser', topics: ['Visual and Snapshot Testing', 'Cross-Browser and Responsive Testing'] },
      { label: 'Scale and Debug', topics: ['Parallelism, Sharding, and Test Isolation', 'Debugging and Troubleshooting'] },
      { label: 'Quality and Reporting', topics: ['Accessibility Testing', 'Reporting', 'Test Organization and Tagging'] },
      { label: 'CI and Capstone', topics: ['Continuous Integration', 'Comparing UI-Level and API-Level Testing'] },
      { label: 'AI and Agents', topics: ['Playwright Test Agents', 'Playwright MCP', 'Self-Healing Tests', 'When to Use Agents vs. Manual'] },
    ],
  },
  {
    slug: 'learn-typescript',
    icon: '🔷',
    title: 'Learn TypeScript',
    tag: 'New',
    difficulty: 'Beginner → Advanced',
    hours: '15–20h',
    description: 'The whole TypeScript language, taught simply — from your first typed variable to generics, mapped types, and decorators, all explained in plain English.',
    longDesc: 'One consistent example — BookHaven, a small online bookstore — runs through every module, including the advanced ones, so a harder concept like a mapped type is explained against something you already understand instead of a brand-new example. Nothing is skipped for being "too advanced"; it is taught plainly instead of being cut.',
    hook: 'The whole language, taught in plain English — no jargon walls.',
    outcomes: [
      'Learn TypeScript through one running example, start to finish',
      'Go from your first typed variable to generics and mapped types',
      'Understand why the type system works the way it does',
      'Read and fix real type errors instead of guessing',
    ],
    gradient: 'linear-gradient(135deg, #1E3A8A 0%, #3178C6 100%)',
    topics: ['Types', 'Interfaces', 'Generics', 'Utility Types', 'Async/Await', 'Decorators'],
    videoId: 'z92nyOfBG9g',
    modules: [
      { label: 'Getting Started', topics: ['Setup', 'Why TypeScript'] },
      { label: 'Core Fundamentals', topics: ['Basic Types', 'Objects and Interfaces', 'Type Aliases', 'Functions', 'Arrays and Lists', 'Union Types', 'Type Narrowing', 'Classes', 'Working with Async Code'] },
      { label: 'High-Value Tools', topics: ['Generics', 'Utility Types', 'Enums vs. Union Literals', 'Working with Untyped Code'] },
      { label: 'Advanced and Reference', topics: ['Advanced Generics', 'Conditional and Mapped Types', 'Decorators', 'Modules and Project Structure'] },
      { label: 'Wrapping Up', topics: ['Reading Type Errors', 'Putting It All Together'] },
    ],
  },
  {
    slug: 'typescript-for-test-automation',
    icon: '🧪',
    title: 'TypeScript for Test Automation',
    tag: 'New',
    difficulty: 'Beginner',
    hours: '4–6h',
    description: 'The fastest path from manual testing to writing a confident, typed automated test — no prior programming experience assumed.',
    longDesc: 'A short, testing-only on-ramp for manual testers moving into automation: just enough TypeScript to read a test file, then straight into Jest, typed fixtures, typed API responses, and async test code — all against the same real RBAC healthcare app used across this site\'s automation courses. Not a substitute for learning the language in full; it closes with pointers to Learn TypeScript and to Playwright Test Automation for what comes next.',
    hook: 'From manual tester to shipping typed automated tests — fast.',
    outcomes: [
      'Learn just enough TypeScript to read and write a test file',
      'Get hands-on with Jest, typed fixtures, and async tests',
      'Test a real RBAC application, not a toy example',
      'Walk away ready for a full TypeScript or Playwright course',
    ],
    gradient: 'linear-gradient(135deg, #6A1B9A 0%, #AB47BC 100%)',
    topics: ['TypeScript Basics', 'Jest', 'Typed Fixtures', 'Async/Await', 'RBAC Testing'],
    videoId: 'z92nyOfBG9g',
    sut: {
      label: 'System Under Test',
      repoUrl: 'https://github.com/codedbyabhishekc/rbac-healthcare-system',
      repoName: 'codedbyabhishekc/rbac-healthcare-system',
      description: 'A 4-role RBAC healthcare app (admin / doctor / nurse / patient) with an Express + SQLite backend, JWT auth, and Swagger docs. This course only needs the backend running — every example calls its REST API directly with fetch, no browser involved.',
      cloneCommand: 'git clone https://github.com/codedbyabhishekc/rbac-healthcare-system.git\ncd rbac-healthcare-system',
      steps: [
        'Only the backend is needed for this course: cd backend && npm install && mkdir database, add a .env with PORT=5000, JWT_SECRET=<any-long-random-string>, and NODE_ENV=development, then npm start.',
        'Seed data: npm run seed — creates 3 Admins, 8 Doctors, 7 Nurses, 15 Patients, 22 Appointments, and 15 Medical Records. Default admin login: admin / admin123.',
        "Confirm it's up at http://localhost:5000/api-docs — the Swagger UI lists every endpoint this course calls.",
      ],
      docsLink: '/docs/typescript-for-test-automation/setup',
    },
    modules: [
      { label: 'Getting Started', topics: ['Setup'] },
      { label: 'Core TypeScript for Tests', topics: ['Just Enough TypeScript to Read a Test', 'Functions and Imports', 'Classes, Briefly'] },
      { label: 'Testing with Jest', topics: ['Setting Up Jest', 'Typing Test Data and Fixtures', 'Typing API Responses', 'Understanding Async Test Code'] },
      { label: 'Putting It Together', topics: ['Structuring a Simple Typed Test Project', 'Capstone: RBAC Permission Matrix'] },
    ],
  },
  {
    slug: 'python-for-test-automation',
    icon: '🧪',
    title: 'Python for Test Automation',
    tag: 'New',
    difficulty: 'Beginner',
    hours: '4–6h',
    description: 'The fastest path from manual testing to writing a confident, automated Python test — no prior programming experience assumed.',
    longDesc: 'A short, testing-only on-ramp for manual testers moving into automation: just enough Python to read a test file, then straight into pytest, test data with lists/dicts/sets, type hints, and calling real APIs — all against the same real RBAC healthcare app used across this site\'s automation courses. Not a substitute for learning the language in full; it closes with pointers to Python for AI Engineers and to realistic next steps like Selenium, Playwright\'s Python bindings, and API testing.',
    hook: 'From manual tester to shipping automated Python tests — fast.',
    outcomes: [
      'Learn just enough Python to read and write a test file',
      'Get hands-on with pytest, fixtures, and real API calls',
      'Test a real RBAC application, not a toy example',
      'Walk away ready for a full Python or automation course',
    ],
    gradient: 'linear-gradient(135deg, #1E4D8C 0%, #4DD0E1 100%)',
    topics: ['Python Basics', 'pytest', 'Fixtures', 'Type Hints', 'RBAC Testing'],
    videoId: 'z92nyOfBG9g',
    sut: {
      label: 'System Under Test',
      repoUrl: 'https://github.com/codedbyabhishekc/rbac-healthcare-system',
      repoName: 'codedbyabhishekc/rbac-healthcare-system',
      description: 'A 4-role RBAC healthcare app (admin / doctor / nurse / patient) with an Express + SQLite backend, JWT auth, and Swagger docs. This course only needs the backend running — every example calls its REST API directly with requests, no browser involved.',
      cloneCommand: 'git clone https://github.com/codedbyabhishekc/rbac-healthcare-system.git\ncd rbac-healthcare-system',
      steps: [
        'Only the backend is needed for this course: cd backend && npm install && mkdir database, add a .env with PORT=5000, JWT_SECRET=<any-long-random-string>, and NODE_ENV=development, then npm start.',
        'Seed data: npm run seed — creates 3 Admins, 8 Doctors, 7 Nurses, 15 Patients, 22 Appointments, and 15 Medical Records. Default admin login: admin / admin123.',
        "Confirm it's up at http://localhost:5000/api-docs — the Swagger UI lists every endpoint this course calls.",
      ],
      docsLink: '/docs/python-for-test-automation/setup',
    },
    modules: [
      { label: 'Getting Started', topics: ['Setup'] },
      { label: 'Core Python for Tests', topics: ['Just Enough Python to Read a Test', 'Functions and Imports', 'Classes, Briefly'] },
      { label: 'Testing with pytest', topics: ['Setting Up pytest', 'Lists, Dicts, and Sets', 'Type Hints for Test Data', 'Calling APIs and Understanding Responses'] },
      { label: 'Putting It Together', topics: ['Fixtures and pytest Conventions', 'Structuring a Simple Test Project', 'Capstone: RBAC Permission Matrix'] },
    ],
  },
];

// docsSlug is the real Docusaurus docs folder name a course's lessons live
// under — it's what DocRoot's access guard and the middleware/RPC key off.
// It defaults to `slug` and only needs to be set explicitly when the two
// diverge (see ai-engineering-crash-course above). `url` (the marketing/
// catalog route) always derives from `slug`, never set per-course.
//
// Built via .map() (a new array) rather than mutating `courses` in place —
// TypeScript infers a plain .js module's export type from the object
// literals as written, not from later mutations, so an in-place loop here
// would make `url`/`docsSlug` invisible to consumers doing `tsc --noEmit`.
const normalizedCourses = courses.map((course) => ({
  ...course,
  docsSlug: course.docsSlug ?? course.slug,
  url: `/course/${course.slug}`,
}));

export default normalizedCourses;